FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app

RUN pip install --upgrade pip setuptools && \
    pip install "pyarrow==14.0.2" "huggingface_hub==0.20.3" "fsspec==2023.10.0" && \
    pip install -r requirements.txt

COPY run.py /app
COPY src /app/src

ENTRYPOINT ["python3", "run.py"]
